import { useState } from 'react';
import { 
  FileText, 
  X, 
  Printer, 
  Download, 
  Copy, 
  Check, 
  ShieldCheck, 
  Building2, 
  AlertTriangle,
  FileCheck
} from 'lucide-react';

export default function ExportReportModal({ 
  isOpen, 
  onClose, 
  scenario, 
  assessment 
}) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !scenario) return null;

  const currentAssessment = assessment || {
    assessment_id: `ASM-${scenario.id.toUpperCase()}`,
    vision: {
      damage_detected: scenario.ground_truth_severity !== 'NO_DAMAGE',
      damage_type: scenario.type,
      damage_score: scenario.predicted_confidence || 0.85,
      confidence: scenario.predicted_confidence || 0.92,
      evidence: [
        'Visible roof fractures and concrete rubble spreading along facade',
        'Severe perimeter wall degradation',
        'Structural column shearing'
      ]
    },
    geo_context: {
      population_affected: scenario.population_affected,
      criticality: scenario.criticality,
      flood_zone: scenario.flood_zone
    },
    assessment: {
      severity: scenario.predicted_severity || scenario.ground_truth_severity,
      severity_score: scenario.predicted_confidence || 0.85
    },
    claim_analysis: {
      risk: scenario.claim_risk,
      consistent: scenario.claim_risk !== 'HIGH'
    },
    priority: {
      level: scenario.ground_truth_severity,
      score: scenario.criticality || 0.88
    },
    final_decision: {
      status: scenario.claim_status || 'UNDER_REVIEW',
      recommended_action: 'PRIORITY_DISPATCH'
    }
  };

  const handleCopyMarkdown = () => {
    const mdContent = `
# DISASTER INCIDENT BRIEF & DAMAGE ASSESSMENT REPORT
**Document Control ID:** ${currentAssessment.assessment_id || 'ASM-DOC-001'}  
**Classification:** RESTRICTED // EMERGENCY RELIEF DIRECTIVE  
**Date:** ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}  
**Target Asset:** ${scenario.asset_id} (${scenario.label})  
**Coordinates:** Lat ${scenario.lat}, Lon ${scenario.lon} (${scenario.region})  

---

### 1. SATELLITE OPTICAL RECONNAISSANCE
- **Disaster Type:** ${scenario.type}
- **Damage Severity:** ${currentAssessment.assessment?.severity || scenario.ground_truth_severity}
- **Model Confidence:** ${((currentAssessment.vision?.confidence || scenario.predicted_confidence) * 100).toFixed(1)}%
- **Damage Detection Score:** ${currentAssessment.vision?.damage_score || 0.85}
- **Structural Integrity:** ${scenario.structural_integrity || 'UNSAFE'}

### 2. GEOSPATIAL & HUMAN IMPACT
- **Population at Risk:** ${scenario.population_affected} residents
- **Infrastructure Criticality:** ${scenario.criticality * 100}%
- **Flood Zone Inundation:** ${scenario.flood_zone ? 'YES - ACTIVE' : 'NO'}

### 3. CLAIM & FINANCIAL VERIFICATION
- **Claim ID:** ${scenario.claim_id}
- **Policy Holder:** ${scenario.policy_holder}
- **Claimed Amount:** $${scenario.claim_amount?.toLocaleString()}
- **AI Assessed Loss:** $${scenario.estimated_damage?.toLocaleString()}
- **Fraud Risk Tier:** ${scenario.claim_risk}
- **Discrepancy:** $${(scenario.claim_amount - scenario.estimated_damage).toLocaleString()}

### 4. FIELD AUDIT & HUMAN DECISION
- **Field Responder:** ${scenario.responder_name} (${scenario.responder_id})
- **GPS Accuracy:** ${scenario.gps_accuracy}
- **HITL Status:** ${currentAssessment.final_decision?.status || 'APPROVED'}
- **Field Notes:** ${scenario.field_report}

---
*Generated by DisasterIQ Enterprise EOC v2.4 (Local On-Prem Restricted Boundary)*
`;

    navigator.clipboard.writeText(mdContent.trim());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    const reportData = {
      incident_brief: {
        asset_id: scenario.asset_id,
        scenario_id: scenario.id,
        region: scenario.region,
        lat: scenario.lat,
        lon: scenario.lon,
        type: scenario.type,
        severity: currentAssessment.assessment?.severity || scenario.ground_truth_severity,
        confidence: currentAssessment.vision?.confidence || scenario.predicted_confidence,
        population_affected: scenario.population_affected,
        claim: {
          id: scenario.claim_id,
          holder: scenario.policy_holder,
          claimed: scenario.claim_amount,
          assessed: scenario.estimated_damage,
          risk: scenario.claim_risk,
          status: currentAssessment.final_decision?.status || scenario.claim_status
        },
        field_log: {
          responder: scenario.responder_name,
          accuracy: scenario.gps_accuracy,
          notes: scenario.field_report
        },
        timestamp: new Date().toISOString()
      }
    };

    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(reportData, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `disaster_report_${scenario.asset_id}_${Date.now()}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm font-mono text-xs">
      <div className="relative w-full max-w-3xl max-h-[90vh] flex flex-col rounded-2xl border border-slate-700 bg-[#0B111E] text-slate-100 shadow-2xl overflow-hidden">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-slate-800 bg-[#0E1626] px-5 py-4">
          <div className="flex items-center gap-2.5">
            <div className="h-8 w-8 rounded-lg bg-orange-950 border border-orange-500/50 flex items-center justify-center text-orange-400">
              <FileText className="h-4 w-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white uppercase tracking-wider">
                Official Disaster Assessment Dossier
              </h3>
              <p className="text-[10px] text-slate-400 font-mono">
                Asset: {scenario.asset_id} • Classification: RESTRICTED LOCAL BOUNDARY
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition cursor-pointer"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Modal Body: Printable Dossier Layout */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6 bg-[#070B13] text-slate-200 printable-dossier">
          
          {/* Dossier Header Banner */}
          <div className="p-4 rounded-xl border border-slate-800 bg-[#0E1626] flex items-center justify-between">
            <div>
              <span className="text-[10px] font-bold text-orange-400 uppercase tracking-widest block">
                NATIONAL EMERGENCY MANAGEMENT DIRECTIVE
              </span>
              <h2 className="text-base font-bold text-white mt-0.5">
                {scenario.label}
              </h2>
              <p className="text-xs text-slate-400 mt-1">
                Region: <span className="text-slate-200">{scenario.region}</span> • Coordinates: <span className="text-cyan-400">{scenario.lat}°N, {scenario.lon}°W</span>
              </p>
            </div>

            <div className="text-right">
              <span className="inline-block px-3 py-1 rounded text-xs font-bold uppercase border bg-rose-950/80 border-rose-500 text-rose-300">
                {currentAssessment.assessment?.severity || scenario.ground_truth_severity} SEVERITY
              </span>
              <p className="text-[10px] text-slate-400 mt-1 font-mono">
                Confidence: {((currentAssessment.vision?.confidence || scenario.predicted_confidence) * 100).toFixed(0)}%
              </p>
            </div>
          </div>

          {/* 3-Column Metrics Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
            <div className="p-3.5 rounded-xl border border-slate-800 bg-[#0B111E]">
              <span className="text-[10px] text-slate-400 font-bold uppercase block">1. Optical Damage</span>
              <p className="text-sm font-bold text-white mt-1">{scenario.type}</p>
              <p className="text-[11px] text-slate-400 mt-0.5">{scenario.structural_integrity}</p>
            </div>

            <div className="p-3.5 rounded-xl border border-slate-800 bg-[#0B111E]">
              <span className="text-[10px] text-slate-400 font-bold uppercase block">2. Population Impact</span>
              <p className="text-sm font-bold text-cyan-400 mt-1">{scenario.population_affected} Affected</p>
              <p className="text-[11px] text-slate-400 mt-0.5">Criticality: {(scenario.criticality * 100).toFixed(0)}%</p>
            </div>

            <div className="p-3.5 rounded-xl border border-slate-800 bg-[#0B111E]">
              <span className="text-[10px] text-slate-400 font-bold uppercase block">3. Claim Verification</span>
              <p className="text-sm font-bold text-emerald-400 mt-1">${scenario.estimated_damage?.toLocaleString()}</p>
              <p className="text-[11px] text-slate-400 mt-0.5">Risk Tier: {scenario.claim_risk}</p>
            </div>
          </div>

          {/* Detailed Evidence & Field Observations */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-white uppercase tracking-wider border-b border-slate-800 pb-1">
              Field Reconnaissance & Agent Evidence Notes
            </h4>
            <div className="p-3.5 rounded-xl border border-slate-800 bg-[#080D18] space-y-2">
              <p className="text-xs text-slate-300 leading-relaxed">
                <strong className="text-orange-400">Field Observer Log:</strong> {scenario.field_report}
              </p>
              <p className="text-[11px] text-slate-400 pt-2 border-t border-slate-800">
                Verified by: <span className="text-slate-200">{scenario.responder_name}</span> (GPS Accuracy: {scenario.gps_accuracy})
              </p>
            </div>
          </div>

          {/* Claim Financial Table */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-white uppercase tracking-wider border-b border-slate-800 pb-1">
              Relief Claim Audit & Payout Breakdown
            </h4>
            <div className="overflow-x-auto rounded-xl border border-slate-800 bg-[#080D18]">
              <table className="w-full text-left">
                <thead className="bg-slate-900/60 text-[10px] text-slate-400 uppercase">
                  <tr>
                    <th className="p-2.5">Claim ID</th>
                    <th className="p-2.5">Policy Holder</th>
                    <th className="p-2.5">Claimed Amount</th>
                    <th className="p-2.5">Satellite Verified</th>
                    <th className="p-2.5">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800 text-xs text-slate-200">
                  <tr>
                    <td className="p-2.5 font-bold">{scenario.claim_id}</td>
                    <td className="p-2.5">{scenario.policy_holder}</td>
                    <td className="p-2.5 font-bold">${scenario.claim_amount?.toLocaleString()}</td>
                    <td className="p-2.5 font-bold text-emerald-400">${scenario.estimated_damage?.toLocaleString()}</td>
                    <td className="p-2.5">
                      <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-blue-950 text-blue-300 border border-blue-500/40">
                        {currentAssessment.final_decision?.status || scenario.claim_status}
                      </span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

        </div>

        {/* Modal Footer Controls */}
        <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-800 bg-[#0E1626] px-5 py-3">
          <div className="flex items-center gap-1.5 text-[10px] text-emerald-400 font-bold">
            <ShieldCheck className="h-4 w-4" />
            <span>Cryptographically Signed On-Prem Dossier</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-700 text-slate-200 hover:text-white hover:border-slate-600 transition cursor-pointer"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? 'Copied MD!' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={handleDownloadJSON}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-700 text-slate-200 hover:text-white hover:border-slate-600 transition cursor-pointer"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Export JSON</span>
            </button>

            <button
              onClick={() => window.print()}
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg bg-orange-600 hover:bg-orange-500 text-white font-bold transition shadow-lg shadow-orange-950/40 cursor-pointer"
            >
              <Printer className="h-3.5 w-3.5" />
              <span>Print Dossier / PDF</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
